### PR TITLE
fixed loader

### PR DESCRIPTION
**Pull request by RaunaqChawhan**
#15 

Improved the previous loader with a Captain America shield spinning.

### CODE REVIEW

**Comment by sudipt1999** [comment]
Please attach the screenshot of loader

**Comment by RaunaqChawhan** [comment]
Sure. I've attached the screenshot with this
MARVEL-GoogleChrome13-10-201918

**Comment by sudipt1999** [comment]
Great work with cap loader! I really loved it!

**Comment by RaunaqChawhan** [comment]
Thank you! I really loved it too getting to work on it!

**Pull request merged**
